repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict

  # - repo: local
  #   hooks:
  #     - id: py_black
  #       language: system
  #       name: Format code in src using black
  #       entry: black --include '\.py$' src --diff --color --config pyproject.toml
  #       pass_filenames: false

  #     - id: py_isort
  #       language: system
  #       name: organise imports in .py files
  #       entry: isort src --float-to-top
  #       pass_filenames: false

      # - id: py_mypy
      #   language: system
      #   name: type check .py files
      #   entry: mypy src
      #   pass_filenames: false

      # - id: ipynb_black
      #   language: system
      #   name: format notebooks
      #   entry: nbqa black --include '\.ipynb$' src --diff --color --ipynb --config pyproject.toml
      #   pass_filenames: false

      # - id: ipynb_isort
      #   language: system
      #   name: organising imports in notebooks
      #   entry: nbqa isort src --float-to-top
      #   pass_filenames: false